config/routes.rb
Rails.application.routes.draw do
  get 'tr_pendaftarans/index'
  get 'tr_pendaftarans/edit'
  get 'tr_pendaftarans/update'
  get 'tr_pendaftarans/new'
  get 'tr_pendaftarans/create'
  get 'tr_pendaftarans/show'
  get 'tr_pendaftarans/destroy'
  devise_for :users
  resources :tr_pendaftarans
  resources :tr_registrations
  #get 'tr_registrations/index'
  #get 'tr_registrations/edit'
  #get 'tr_registrations/update'
  #get 'tr_registrations/new'
  root to: "tr_pendaftarans#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tr_pendaftaran.rb
class TrPendaftaran < ApplicationRecord
end

app/models/tr_registration.rb
class TrRegistration < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/tr_pendaftarans_controller.rb
class TrPendaftaransController < ApplicationController
  before_action :id_param, only: [:show, :edit, :update, :destroy]
  def index
    @tr_pendaftarans = TrPendaftaran.all
  end

  def edit
  end

  def update
    tr_pendaftarans = TrPendaftaran.where(:id => params[:id])
    tr_pendaftarans.update(tr_pendaftarans_params)
    if tr_pendaftarans
    redirect_to tr_pendaftarans_path, notice: "Data Telah Di Perbaharui"
  else
    render 'edit'
  end
  end

  def new
    @tr_pendaftarans = TrPendaftaran.new
  end

  def create
    @tr_pendaftarans = TrPendaftaran.new(tr_pendaftarans_params)

    if @tr_pendaftarans.save
      redirect_to tr_pendaftarans_path, notice: "Terima Kasih Telah Mendaftar di SMK Wikrama Bogor"
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @tr_pendaftarans = TrPendaftaran.find(params[:id])
    @tr_pendaftarans.destroy
    redirect_to tr_pendaftarans_path, notice: "Data Telah Terhapus"
  end
  private
  def tr_pendaftarans_params
    params.require(:tr_pendaftaran).permit(:id, :format, :nis, :nama, :jenis_kelamin, :tempat_lahir, :tanggal_lahir, :alamat, :asal_sekolah, :kelas, :jurusan, :created_by, :updated_by)
  end

  def id_param
    @tr_pendaftarans = TrPendaftaran.find_by(:id=>params[:id])
  end
end

app/controllers/tr_registrations_controller.rb
class TrRegistrationsController < ApplicationController
  def index
  	@tr_registrations = TrRegistration.all
  end

  def edit
  	@tr_registrations = TrRegistration.find(params[:id])
  end

  def update
  	tr_registrations = TrRegistration.where(:id => params[:id])
  	tr_registrations.update(tr_registrations_params)
  	if tr_registrations
  	redirect_to tr_registrations_path, notice: "Data Telah Ter-Update"
  else
  	render 'edit'
  end
  end

  def new
  	@tr_registrations = TrRegistration.new
  end

  def create
  	@tr_registrations = TrRegistration.new(tr_registrations_params)

    if @tr_registrations.save
      redirect_to tr_registrations_path, notice: "Data Telah Ter-Upload"
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
  	@tr_registrations = TrRegistration.find(params[:id])
    @tr_registrations.destroy
    redirect_to tr_registrations_path, notice: "Data Successfuly Deleted"
  end

private
  def tr_registrations_params
    params.require(:tr_registration).permit(:id, :nis, :nama, :jenis_kelamin, :tempat_lahir, :tanggal_lahir, :alamat, :asal_sekolah, :kelas, :jurusan)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tr_pendaftarans_helper.rb
module TrPendaftaransHelper
end

app/helpers/tr_registrations_helper.rb
module TrRegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wikrama</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
<div class="alert alert-info">
  <%= msg %>
</div>
<% end %>
    <div class="container-fluid">
    <%= yield %>
    </div>
  </body>
</html>

app/views/tr_pendaftarans/create.html.erb
<h1>TrPendaftarans#create</h1>
<p>Find me in app/views/tr_pendaftarans/create.html.erb</p>

app/views/tr_pendaftarans/destroy.html.erb
<h1>TrPendaftarans#destroy</h1>
<p>Find me in app/views/tr_pendaftarans/destroy.html.erb</p>

app/views/tr_pendaftarans/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <%= form_for(@tr_pendaftarans) do |tr_pendaftaran| %>
        <div class="form-group">
          <%= tr_pendaftaran.label :Nis %>
          <%= tr_pendaftaran.text_field :nis, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= tr_pendaftaran.label :Nama %>
          <%= tr_pendaftaran.text_field :nama, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :jenis_kelamin %>
          <%= tr_pendaftaran.text_field :jenis_kelamin, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :tempat_lahir %>
          <%= tr_pendaftaran.text_field :tempat_lahir, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :tanggal_lahir %>
          <%= tr_pendaftaran.text_field :tanggal_lahir, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :alamat %>
          <%= tr_pendaftaran.text_field :alamat, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :asal_sekolah %>
          <%= tr_pendaftaran.text_field :asal_sekolah, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :kelas %>
          <%= tr_pendaftaran.text_field :kelas, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :jurusan %>
          <%= tr_pendaftaran.text_field :jurusan, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div style="float: left">
  <%= link_to 'Back', '/tr_pendaftarans', class: 'btn btn-primary' %>
        </div>
        <div style="float: right">
  <%= tr_pendaftaran.submit :Save, class:'btn btn-success' %>
</div>
    <% end %>
  </div>
</div>

app/views/tr_pendaftarans/index.html.erb
<% if current_user.role == "Siswa" %>
<center><h4>Selamat Datang <%= current_user.nama %></h4></center>
<center> <%= link_to 'Daftar Sekarang', tr_pendaftarans_new_path, class: 'btn btn-success' %></center>
<br>
<center><%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'btn btn-secondary') %> </center>
<% end %>
<% if current_user.role == "Admin" %>
<center><h5>Log Siswa </h5></center>
<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">No</th>
      <th scope="col">Nis</th>
      <th scope="col">Nama</th>
      <th scope="col">Jenis Kelamin</th>
      <th scope="col">Tempat Lahir</th>
      <th scope="col">Tanggal Lahir</th>
      <th scope="col">Alamat</th>
      <th scope="col">Asal Sekolah</th>
      <th scope="col">Kelas</th>
      <th scope="col">Jurusan</th>
      <th scope="col" width="300px">Action</th>
    </tr>
  </thead>
  <% @tr_pendaftarans.each_with_index do |t, index| %>
  <tbody>
    <tr>
      <th scope="row"> <%= index + 1 %> </th>
      <td> <%= t.nis %> </td>
      <td> <%= t.nama %> </td>
      <td> <%= t.jenis_kelamin %> </td>
      <td> <%= t.tempat_lahir %> </td>
      <td> <%= t.tanggal_lahir %> </td>
      <td> <%= t.alamat %> </td>
      <td> <%= t.asal_sekolah %> </td>
      <td> <%= t.kelas %> </td>
      <td> <%= t.jurusan %> </td>
      <td class="text-center">
        <%= link_to 'Delete',tr_pendaftaran_path(t), method: :delete, data: {confirm: 'Delete Data ? '}, class: 'btn btn-danger' %>	
        <%= link_to 'Edit', edit_tr_pendaftaran_path(t), class: 'btn btn-primary' %>
      </td>
      <% end %>
    </tr>
  </tbody>
</table>
<br>
<center><%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'btn btn-secondary') %> </center>
<% end %>

app/views/tr_pendaftarans/new.html.erb
<div class="container-fluid">
  <div class="row">
    <%= form_for(@tr_pendaftarans) do |tr_pendaftaran| %>
        <div class="form-group">
          <%= tr_pendaftaran.label :Nis %>
          <%= tr_pendaftaran.text_field :nis, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= tr_pendaftaran.label :Nama %>
          <%= tr_pendaftaran.text_field :nama, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :jenis_kelamin %>
          <%= tr_pendaftaran.text_field :jenis_kelamin, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :tempat_lahir %>
          <%= tr_pendaftaran.text_field :tempat_lahir, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :tanggal_lahir %>
          <%= tr_pendaftaran.text_field :tanggal_lahir, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :alamat %>
          <%= tr_pendaftaran.text_field :alamat, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :asal_sekolah %>
          <%= tr_pendaftaran.text_field :asal_sekolah, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :kelas %>
          <%= tr_pendaftaran.text_field :kelas, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= tr_pendaftaran.label :jurusan %>
          <%= tr_pendaftaran.text_field :jurusan, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>
        <div style="float: left">
  <%= link_to 'Back', '/tr_pendaftarans', class: 'btn btn-primary' %>
        </div>
        <div style="float: right">
  <%= tr_pendaftaran.submit :Save, class:'btn btn-success' %>
</div>
    <% end %>
  </div>
</div>

app/views/tr_pendaftarans/show.html.erb
<center><h4>Terima Kasih Telah Mendaftar Di SMK WIkrama Bogor</h4></center>
<center><%= link_to('Logout', destroy_user_session_path, method: :delete) %> </center>

app/views/tr_pendaftarans/update.html.erb
<h1>TrPendaftarans#update</h1>
<p>Find me in app/views/tr_pendaftarans/update.html.erb</p>

app/views/tr_registrations/create.html.erb
<h1>TrRegistrations#create</h1>
<p>Find me in app/views/tr_registrations/create.html.erb</p>

app/views/tr_registrations/destroy.html.erb
<h1>TrRegistrations#destroy</h1>
<p>Find me in app/views/tr_registrations/destroy.html.erb</p>

app/views/tr_registrations/edit.html.erb
<h1>TrRegistrations#edit</h1>
<p>Find me in app/views/tr_registrations/edit.html.erb</p>

app/views/tr_registrations/index.html.erb
<% if current_user.role == "Siswa" %>
<center><h4>Selamat Datang <%= current_user.nama %></h4></center>
<center> <%= link_to 'Daftar Sekarang', new_tr_registrations_path, class: 'btn btn-success' %></center>
<% end %>

app/views/tr_registrations/new.html.erb
<h1>TrRegistrations#new</h1>
<p>Find me in app/views/tr_registrations/new.html.erb</p>

app/views/tr_registrations/update.html.erb
<h1>TrRegistrations#update</h1>
<p>Find me in app/views/tr_registrations/update.html.erb</p>